nelmio_cors:
    defaults:
        origin_regex: false
        #allow_origin: ['%env(CORS_ALLOW_ORIGIN)%', '^http://nexusapp.enaebl.com:[0-9]+']
        allow_origin: ['http://localhost:8081', 'http://nexusapp.enaebl.com']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        max_age: 3600
    paths:
        '^/api/':
                allow_origin: ['http://localhost:8081', 'http://nexusapp.enaebl.com']
                allow_headers: ['X-Custom-Auth', 'Content-Type', 'Authorization', 'Access-Control-Allow-Origin']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
        '^/':
                origin_regex: false
                allow_origin: ['*']
                allow_headers: ['X-Custom-Auth']
                allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
                max_age: 3600
                hosts: ['^api\.']
